# Generated by Django 5.2.8 on 2025-11-27 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shortlink',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('Actual_URL', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('ex', 'Expired')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
