# Generated by Django 5.2.8 on 2025-11-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('ex', 'Expired')], default='ac'),
        ),
    ]
