# Generated by Django 5.2.8 on 2025-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0002_alter_shortlink_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='status',
            field=models.CharField(choices=[('ac', 'Active'), ('ia', 'Inactive'), ('ex', 'Expired'), ('de', 'Deleted')], default='ac'),
        ),
    ]
